#    snapcraft yaml for performous-snap.
#    Copyright (C) 2021-2024 joker2770
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# After registering a name on build.snapcraft.io, commit an uncommented line:
name: performous-snap
version: '1.3.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: An open-source music and rhythm game. # 79 char long summary
description: |
  An open-source karaoke, band and dancing game where one or more players
  perform a song and the game scores their performances. Supports songs
  in UltraStar, Frets on Fire and StepMania formats. Microphones and
  instruments from SingStar, Guitar Hero and Rock Band as well as
  some dance pads are autodetected.

  Website at http://performous.org/ << If you can't reach it try the
  mirror https://performous.asgardsings.nl
  Wiki at https://github.com/performous/performous/wiki
  Discord at https://discord.gg/NS3m3ad

  For compiling instructions, see docs/Compiling.txt or visit the
  wiki page: https://github.com/performous/performous/wiki/Building-and-installing-from-source

  _More build details: https://github.com/Joker2770/performous-snap_

  Tips: Performous can look for songs from `~/snap/performous-snap/current/`.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core24
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

plugs:
  desktop:
    mount-host-font-cache: false
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  gnome-46-2404:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-46-2404
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404

apps:
  performous-snap:
    command-chain: ["snap/command-chain/alsa-launch"]
    command: usr/local/bin/performous
    environment:
      # pulseaudio
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio"
      SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
      GTK_USE_PORTAL: '1'
    extensions: [gnome]
    plugs:
      - home
      - audio-playback
      - pulseaudio
      - alsa
      - jack1
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - opengl
      - gsettings
      - removable-media
      - mount-observe
        
layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.0:
    bind: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.0
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/webkit2gtk-4.1
  /usr/share/xml/iso-codes:
    bind: $SNAP/gnome-platform/usr/share/xml/iso-codes
  /usr/share/libdrm:
    bind: $SNAP/gpu-2404/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/gpu-2404/drirc.d
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/gpu-2404/X11/XErrorDB
  /usr/share/midi/freepats:
    bind: $SNAP/usr/share/midi/freepats
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/local/share/locale:
    bind: $SNAP/usr/local/share/locale
  /usr/local/share/games/performous:
    bind: $SNAP/usr/local/share/games/performous
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /etc/timidity:
    bind: $SNAP/etc/timidity
  /etc/fonts:
    bind: $SNAP/etc/fonts
    
parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad

  performous-snap:
    after: [alsa-mixin]
    plugin: cmake
    cmake-parameters:
      - "-DCMAKE_CXX_STANDARD=17"
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DCMAKE_INSTALL_PREFIX=/usr/local"
    source: "https://github.com/performous/performous.git"
    source-depth: 1
    source-branch: master
    source-type: git
    build-packages:
      - gcc
      - g++
      - cmake
      - gettext
      - libaubio-dev
      - libavutil-dev
      - libavcodec-dev
      - libavformat-dev
      - libboost-all-dev
      - libboost-dev
      - libboost-iostreams-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - libboost-locale-dev
      - libcairo2-dev
      - libcrypto++-dev
      - libepoxy-dev
      - libfftw3-dev
      - libfmt-dev
      - libfreetype-dev
      - libglibmm-2.4-dev
      - libglm-dev
      - libgmock-dev
      - libgtest-dev
      - libicu-dev
      - libjpeg-dev
      - libjpeg9-dev
      - libopenblas-dev
      - libopencv-dev
      - libopencv-highgui-dev
      - libpango1.0-dev
      - libpng-dev
      - libportmidi-dev
      - librsvg2-dev
      - libswscale-dev
      - libsigc++-2.0-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-ttf-dev
      - libsdl2-mixer-dev
      - libssl-dev
      - libcpprest-dev
      - libxml++2.6-dev
      - nlohmann-json3-dev
      - portaudio19-dev
    stage-packages:
      - libaubio5
      - libavutil59
      - libavcodec61
      - libavformat61
      - libblas3
      - libboost-iostreams1.83.0
      - libboost-locale1.83.0
      - libboost-program-options1.83.0
      - libboost-thread1.83.0
      - libcairo2
      - libcrypto++6
      - libepoxy0
      - libfftw3-double3
      - libfreetype6
      - libglibmm-2.4-1t64
      - libglu1-mesa
      - libicu74
      - libjpeg9
      - liblapack3
      - libmodplug1
      - libopencv-core406t64
      - libopencv-highgui406t64
      - libopenblas-base
      - libopusfile0
      - libgdk-pixbuf2.0-0
      - libportaudio2
      - libportmidi0
      - libpulse0
      - libpng16-16t64
      - libpangocairo-1.0-0
      - libcpprest2.10
      - librsvg2-2
      - libsndfile1
      - libswscale7
      - libsigc++-2.0-0v5
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-ttf-2.0-0
      - libsdl2-mixer-2.0-0
      - libssl3t64
      - libxml++2.6-2v5
      - libx264-164
      - freepats
